name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  mac:
    uses: ./.github/workflows/mac.yml
    secrets: inherit

  windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit

  release:
    needs: [mac, windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: python-3.9.10-nogil-macos.tar.gz

      - uses: actions/download-artifact@v3
        with:
          name: python-3.9.10-amd64.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            python-3.9.10-nogil-macos.tar.gz
            python-3.9.10-amd64.exe
